
# Perturbative order of the computation. 
# 0: LL, 1: NLL, 2: NNLL, 3: NNNLL, -1: NLL', -2: NNLL'
PerturbativeOrder: 3

# Path of the OPE grids
ope:
  grid_file: "../../grids/grids/tmdpdf_u_Q_1.txt"

# Define initial scale for the evolution
Q20: 1.0

# Collinear PDF set and member to be used
pdfset:
  name: "MMHT2014nnlo68cl"
  member: 0

# Collinear FF set and member to be used
ffset:
  name: "MAPFF10NNLOPIp"
  member: 0

# Initial and final scale-variation factors around mub = 2e^{-gamma_E} / b and Q, respectively
TMDscales:
  Ci: 1.0
  Cf: 1.0

# Reference value of alpha_em
alphaem:
  aref: 0.0072973525693
  Qref: 91.1876
  run: true

# qT/Q cut for computation
qToQcut: 0.2

# b-space grid configuration for PyTorch integration for Ogata quadrature
# Used for differentiable trapezoidal integration as alternative to Ogata quadrature
bgrid:
  b_min: 1.0e-3    # Minimum b value (GeV^-1)
  #b_max: 2.0       # Maximum b value (GeV^-1)  
  Nb: 500          # Number of grid points for bT in the Ogata quadrature
